Now can create instnaces in different region and availability zone from the region and zone of the root volume

diff --git a/ec2spotter-remount-root b/ec2spotter-remount-root
--- a/ec2spotter-remount-root
+++ b/ec2spotter-remount-root
@@ -13,7 +13,14 @@ if [ "x$2" = "x" ]; then echo "missing volume name"; exit -1; fi
 
 ROOT_VOL_NAME=$2
 
-ec2spotter_elastic_ip=$3
+if [ "x$3" = "x" ]
+then 
+	echo "missing volume region"; 
+	exit -1; 
+fi
+ROOT_REGION=$3
+
+ec2spotter_elastic_ip=$4
 
 # Get Instance ID and current zone from AWS
 export INSTANCE_ID=`curl -s http://169.254.169.254/latest/meta-data/instance-id`
@@ -32,13 +39,10 @@ export EC2_HOME=$(ls -d ./ec2-api-tools-*)
 export JAVA_HOME=/usr/lib/jvm/default-java
 export ARCH=`uname -i`
 
-
-ROOT_REGION=$SPOT_REGION # By default, we're in the same region
-
 echo "Looking for a volume in $ROOT_REGION with Name = $ROOT_VOL_NAME"
 aws ec2 describe-volumes \
         --filters Name=tag-key,Values="Name" Name=tag-value,Values="$ROOT_VOL_NAME" \
-        --region ${SPOT_REGION} > volumes.tmp || exit -1
+        --region ${ROOT_REGION} > volumes.tmp || exit -1
 
 ROOT_ZONE=$(jq -r '.Volumes[0].AvailabilityZone' volumes.tmp)
 ROOT_VOL=$(jq -r '.Volumes[0].VolumeId' volumes.tmp)
@@ -49,18 +53,20 @@ if [[ $ROOT_ZONE != $SPOT_ZONE ]]; then
     # need to copy the volume across
     echo "Volume $ROOT_VOL is in another Availability Zone"
     echo "Creating a snapshot of the volume"
-    SNAPSHOT=$(${APIBIN}/ec2-create-snapshot --region ${ROOT_REGION} $ROOT_VOL --description 'ec2-spotter temporary snapshot ok to delete' | awk '{print $2}')
-    
+    # SNAPSHOT=$(${APIBIN}/ec2-create-snapshot --region ${ROOT_REGION} $ROOT_VOL --description 'ec2-spotter temporary snapshot ok to delete' | awk '{print $2}')
+	aws ec2 create-snapshot --region ${ROOT_REGION} --volume-id $ROOT_VOL --description 'ec2-spotter temporary snapshot ok to delete' > snapshot.tmp || exit -1
+	SNAPSHOT=$(jq -r '.SnapshotId' snapshot.tmp)
+
     echo "Snapshot $SNAPSHOT created. Waiting for completion"
     # Keep checking to see that snapshot has been created
     count=0
     while /bin/true
     do
-        sleep 30
-        eval count=$((count+30))
+        sleep 5
+        eval count=$((count+5))
         echo "... $count seconds gone. Still waiting..."
-        STATUS=$(${APIBIN}/ec2-describe-snapshots --region ${ROOT_REGION} ${SNAPSHOT} | grep completed)
-
+        # STATUS=$(${APIBIN}/ec2-describe-snapshots --region ${ROOT_REGION} ${SNAPSHOT} | grep completed)
+		STATUS=$(aws ec2 describe-snapshots --snapshot-ids ${SNAPSHOT} --region ${ROOT_REGION} | grep completed)
         [[ ! -z $STATUS ]] && break
     done
     echo "Snapshot $SNAPSHOT created successfully"
@@ -68,18 +74,22 @@ if [[ $ROOT_ZONE != $SPOT_ZONE ]]; then
     echo ""
     
     if [[ $SPOT_REGION != $ROOT_REGION ]]; then
-	    NEW_SNAPSHOT=$(${APIBIN}/ec2-copy-snapshot -r ${ROOT_REGION} -s ${SNAPSHOT} | awk '{print $2}')
-    		
+	    # NEW_SNAPSHOT=$(${APIBIN}/ec2-copy-snapshot -r ${ROOT_REGION} -s ${SNAPSHOT} | awk '{print $2}')
+		aws ec2 copy-snapshot \
+			--source-region ${ROOT_REGION} --region ${SPOT_REGION} \
+			--source-snapshot-id ${SNAPSHOT} --destination-region ${SPOT_REGION} > new_snapshot.tmp || exit -1
+		NEW_SNAPSHOT=$(jq -r '.SnapshotId' new_snapshot.tmp)
 	    echo "Copying snapshot from $ROOT_REGION to $SPOT_REGION with name $NEW_SNAPSHOT. Waiting for completion"		
 			
 	    # Keep checking to see that snapshot has been copied		
 	    count=0		
 	    while /bin/true		
 	    do		
-		sleep 30		
-		eval count=$((count+30))		
-		echo "... $count seconds gone. Still waiting..."		
-		STATUS=$(${APIBIN}/ec2-describe-snapshots ${NEW_SNAPSHOT} | grep completed)		
+			sleep 5		
+			eval count=$((count+5))		
+			echo "... $count seconds gone. Still waiting..."		
+			# STATUS=$(${APIBIN}/ec2-describe-snapshots ${NEW_SNAPSHOT} | grep completed)
+			STATUS=$(aws ec2 describe-snapshots --snapshot-ids ${NEW_SNAPSHOT} --region ${SPOT_REGION} | grep completed)
 			
 	       [[ ! -z $STATUS ]] && break		
 	    done		
@@ -92,18 +102,20 @@ if [[ $ROOT_ZONE != $SPOT_ZONE ]]; then
     fi
 
     # create volume from this new snapshot
-    NEW_VOLUME=$(${APIBIN}/ec2-create-volume --snapshot ${NEW_SNAPSHOT} -z ${SPOT_ZONE} --type $ROOT_TYPE | awk '{print $2}')
+    #NEW_VOLUME=$(${APIBIN}/ec2-create-volume --snapshot ${NEW_SNAPSHOT} -z ${SPOT_ZONE} --type $ROOT_TYPE | awk '{print $2}')
+	aws ec2 create-volume --snapshot-id ${NEW_SNAPSHOT} --availability-zone ${SPOT_ZONE} --volume-type $ROOT_TYPE --region ${SPOT_REGION} > new_volume.tmp || exit -1
+	NEW_VOLUME=$(jq -r '.VolumeId' new_volume.tmp)
     echo "Creating volume $NEW_VOLUME from $NEW_SNAPSHOT. Waiting for completion"
     
     # Keep checking to see that volume has been created
     count=0
     while /bin/true
     do
-        sleep 30
-        eval count=$((count+30))
+        sleep 5
+        eval count=$((count+5))
         echo "... $count seconds gone. Still waiting..."
-        STATUS=$(${APIBIN}/ec2-describe-volumes ${NEW_VOLUME} | grep available)
-
+        #STATUS=$(${APIBIN}/ec2-describe-volumes ${NEW_VOLUME} | grep available)
+		STATUS=$(aws ec2 describe-volumes --volume-ids ${NEW_VOLUME} --region ${SPOT_REGION} | grep available)
         [[ ! -z $STATUS ]] && break
     done
     
@@ -111,8 +123,9 @@ if [[ $ROOT_ZONE != $SPOT_ZONE ]]; then
     echo "------------------------------------------------"
 
     echo "Renaming the old volume"
-    aws ec2 create-tags --resources ${ROOT_VOL} --tags Key=Name,Value="${ROOT_VOL_NAME}-is-now-$NEW_VOLUME" --region ${SPOT_REGION}
-
+    aws ec2 create-tags --resources ${ROOT_VOL} --tags Key=Name,Value="${ROOT_VOL_NAME}-is-now-$NEW_VOLUME" --region ${ROOT_REGION}
+	echo "Renaming the new volume"
+	aws ec2 create-tags --resources ${NEW_VOLUME} --tags Key=Name,Value="${ROOT_VOL_NAME}" --region ${SPOT_REGION}
     PERSISTENT_ROOT_VOLUME=${NEW_VOLUME}
 else
     echo "Using the volume as-is, no migration needed"
@@ -122,7 +135,8 @@ fi
 echo ""
 echo "Attaching volume $PERSISTENT_ROOT_VOLUME as /dev/sdf"
 # Attach volume
-${APIBIN}/ec2-attach-volume $PERSISTENT_ROOT_VOLUME -d /dev/sdf --instance $INSTANCE_ID || exit -1
+#${APIBIN}/ec2-attach-volume $PERSISTENT_ROOT_VOLUME -d /dev/sdf --instance $INSTANCE_ID || exit -1
+aws ec2 attach-volume --volume-id $PERSISTENT_ROOT_VOLUME --instance-id $INSTANCE_ID --device /dev/sdf --region ${SPOT_REGION} || exit -1
 
 while ! lsblk /dev/xvdf
 do
